<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento ENTERPRISE edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Advancedsearch
 * @version    1.3.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>

<div id="test_connection_container">
    <div>
        <?php if ($_statusCode = $this->getStatusCode()): ?>
            <?php if ($_statusCode == '200'): ?>
                <div style="color: green; font-weight: bold;"><?php echo $this->__('Connection successfully established') ?></div>
            <?php elseif ($_statusCode == '404'): ?>
                <div style="color: red; font-weight: bold;"><?php echo $this->__('The Doppler API is not currently available, please try later') ?></div>
            <?php else: ?>
                <div style="color: red; font-weight: bold;"><?php echo $this->__('Your credentials are not valid, please check your username and API key and try again') ?></div>
            <?php endif ?>
        <?php else: ?>
            <div><?php echo $this->__('Please, add your credentials above and save this page to test your API connection') ?></div>
        <?php endif ?>
    </div>
</div>